### ISSUE TITLE
Is this a pull from steven's PyPangolin or Uoip's pangolin

### ISSUE THREAD

**Issue by clmnin** [ankurhanda/Pangolin-local#1]
Hey Ankur,
Is this a pull from Steven's [Pypangolin](https://github.com/stevenlovegrove/Pangolin) or from uopi's [pangolin](https://github.com/uoip/pangolin)? I'm just asking because I'm currently facing some issues `importing` uoip's `pangolin` but steven's work perfectly fine. (Issue [11](https://github.com/uoip/pangolin/issues/11)).
And so if you have any clue to fix this or if yours work and have `DrawLines, DrawPoints, etc` API calls, I can use yours too.

**Comment by ankurhanda** [comment]
I didn't use any python on it so unfortunately I don't know much about the issues in python - I used C++ pangolin which was Steve Lovegrove's github fork. Thank you.

**Comment by clmnin** [comment]
Alright. Thank you. I'll close this issue.
